---
apiVersion: v1
kind: ConfigMap
data:
  mapRoles: |
    - rolearn: |
        arn:aws:iam::248616454243:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::248616454243:user/chisama_udacity
      username: chisama_udacity
      groups:
        - system:masters
